// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addParticipant = `-- name: AddParticipant :exec
INSERT INTO conversation_participants (conversation_id, user_id, joined_at)
VALUES ($1, $2, NOW())
ON CONFLICT DO NOTHING
`

type AddParticipantParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) error {
	_, err := q.db.Exec(ctx, addParticipant, arg.ConversationID, arg.UserID)
	return err
}

const countDLQEvents = `-- name: CountDLQEvents :one
SELECT COUNT(*) FROM outbox_dlq
`

func (q *Queries) CountDLQEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDLQEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDLQEventsByAggregateType = `-- name: CountDLQEventsByAggregateType :one
SELECT COUNT(*) FROM outbox_dlq WHERE aggregate_type = $1
`

func (q *Queries) CountDLQEventsByAggregateType(ctx context.Context, aggregateType string) (int64, error) {
	row := q.db.QueryRow(ctx, countDLQEventsByAggregateType, aggregateType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDLQEvent = `-- name: DeleteDLQEvent :exec
DELETE FROM outbox_dlq WHERE id = $1
`

func (q *Queries) DeleteDLQEvent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDLQEvent, id)
	return err
}

const deleteOutboxEvent = `-- name: DeleteOutboxEvent :exec
DELETE FROM outbox WHERE id = $1
`

func (q *Queries) DeleteOutboxEvent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOutboxEvent, id)
	return err
}

const getAndLockUnprocessedOutbox = `-- name: GetAndLockUnprocessedOutbox :many
SELECT id, aggregate_type, aggregate_id, payload, created_at, processed_at, retry_count, last_retry_at
FROM outbox
WHERE processed_at IS NULL
ORDER BY created_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) GetAndLockUnprocessedOutbox(ctx context.Context, limit int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, getAndLockUnprocessedOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.Payload,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.RetryCount,
			&i.LastRetryAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAndLockUnprocessedOutboxWithRetry = `-- name: GetAndLockUnprocessedOutboxWithRetry :many
SELECT id, aggregate_type, aggregate_id, payload, created_at, processed_at, retry_count, last_retry_at
FROM outbox
WHERE processed_at IS NULL
  AND retry_count < $2
  AND (
    last_retry_at IS NULL 
    OR last_retry_at < NOW() - ($3::interval)
  )
ORDER BY created_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type GetAndLockUnprocessedOutboxWithRetryParams struct {
	Limit      int32           `json:"limit"`
	RetryCount int32           `json:"retry_count"`
	Column3    pgtype.Interval `json:"column_3"`
}

func (q *Queries) GetAndLockUnprocessedOutboxWithRetry(ctx context.Context, arg GetAndLockUnprocessedOutboxWithRetryParams) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, getAndLockUnprocessedOutboxWithRetry, arg.Limit, arg.RetryCount, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.Payload,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.RetryCount,
			&i.LastRetryAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversationsForUser = `-- name: GetConversationsForUser :many
SELECT 
    c.id,
    c.last_message_content,
    c.last_message_at,
    (
        SELECT COUNT(*) 
        FROM messages m 
        WHERE m.conversation_id = c.id 
          AND m.created_at > cp.last_read_at
    ) AS unread_count
FROM conversations c
JOIN conversation_participants cp ON c.id = cp.conversation_id
WHERE cp.user_id = $1
  AND ($2::timestamptz IS NULL OR c.last_message_at < $2::timestamptz)
ORDER BY c.last_message_at DESC
LIMIT $3
`

type GetConversationsForUserParams struct {
	UserID  pgtype.UUID        `json:"user_id"`
	Column2 pgtype.Timestamptz `json:"column_2"`
	Limit   int32              `json:"limit"`
}

type GetConversationsForUserRow struct {
	ID                 pgtype.UUID        `json:"id"`
	LastMessageContent pgtype.Text        `json:"last_message_content"`
	LastMessageAt      pgtype.Timestamptz `json:"last_message_at"`
	UnreadCount        int64              `json:"unread_count"`
}

func (q *Queries) GetConversationsForUser(ctx context.Context, arg GetConversationsForUserParams) ([]GetConversationsForUserRow, error) {
	rows, err := q.db.Query(ctx, getConversationsForUser, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationsForUserRow
	for rows.Next() {
		var i GetConversationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.LastMessageContent,
			&i.LastMessageAt,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDLQEvents = `-- name: GetDLQEvents :many
SELECT id, original_event_id, aggregate_type, aggregate_id, payload, error_message, retry_count, original_created_at, moved_to_dlq_at
FROM outbox_dlq
ORDER BY moved_to_dlq_at DESC
LIMIT $1
`

func (q *Queries) GetDLQEvents(ctx context.Context, limit int32) ([]OutboxDlq, error) {
	rows, err := q.db.Query(ctx, getDLQEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxDlq
	for rows.Next() {
		var i OutboxDlq
		if err := rows.Scan(
			&i.ID,
			&i.OriginalEventID,
			&i.AggregateType,
			&i.AggregateID,
			&i.Payload,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.OriginalCreatedAt,
			&i.MovedToDlqAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDLQEventsByAggregateType = `-- name: GetDLQEventsByAggregateType :many
SELECT id, original_event_id, aggregate_type, aggregate_id, payload, error_message, retry_count, original_created_at, moved_to_dlq_at
FROM outbox_dlq
WHERE aggregate_type = $1
ORDER BY moved_to_dlq_at DESC
LIMIT $2
`

type GetDLQEventsByAggregateTypeParams struct {
	AggregateType string `json:"aggregate_type"`
	Limit         int32  `json:"limit"`
}

func (q *Queries) GetDLQEventsByAggregateType(ctx context.Context, arg GetDLQEventsByAggregateTypeParams) ([]OutboxDlq, error) {
	rows, err := q.db.Query(ctx, getDLQEventsByAggregateType, arg.AggregateType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxDlq
	for rows.Next() {
		var i OutboxDlq
		if err := rows.Scan(
			&i.ID,
			&i.OriginalEventID,
			&i.AggregateType,
			&i.AggregateID,
			&i.Payload,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.OriginalCreatedAt,
			&i.MovedToDlqAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessages = `-- name: GetMessages :many
SELECT id, conversation_id, sender_id, content, created_at
FROM messages
WHERE conversation_id = $1
	AND (
		$2::timestamptz IS NULL
		OR created_at < $2::timestamptz
	)
ORDER BY created_at DESC
LIMIT $3
`

type GetMessagesParams struct {
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Before         pgtype.Timestamptz `json:"before"`
	Limit          int32              `json:"limit"`
}

func (q *Queries) GetMessages(ctx context.Context, arg GetMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessages, arg.ConversationID, arg.Before, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnprocessedOutbox = `-- name: GetUnprocessedOutbox :many
SELECT id, aggregate_type, aggregate_id, payload, created_at, processed_at, retry_count, last_retry_at
FROM outbox
WHERE processed_at IS NULL
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetUnprocessedOutbox(ctx context.Context, limit int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, getUnprocessedOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.Payload,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.RetryCount,
			&i.LastRetryAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementOutboxRetry = `-- name: IncrementOutboxRetry :exec
UPDATE outbox
SET retry_count = retry_count + 1,
    last_retry_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementOutboxRetry(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementOutboxRetry, id)
	return err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (conversation_id, sender_id, content)
VALUES ($1, $2, $3)
RETURNING id, conversation_id, sender_id, content, created_at
`

type InsertMessageParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	SenderID       pgtype.UUID `json:"sender_id"`
	Content        string      `json:"content"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage, arg.ConversationID, arg.SenderID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (aggregate_type, aggregate_id, payload)
VALUES ($1, $2, $3)
`

type InsertOutboxParams struct {
	AggregateType string      `json:"aggregate_type"`
	AggregateID   pgtype.UUID `json:"aggregate_id"`
	Payload       []byte      `json:"payload"`
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox, arg.AggregateType, arg.AggregateID, arg.Payload)
	return err
}

const markAsRead = `-- name: MarkAsRead :exec
UPDATE conversation_participants
SET last_read_at = NOW()
WHERE conversation_id = $1
  AND user_id = $2
`

type MarkAsReadParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) MarkAsRead(ctx context.Context, arg MarkAsReadParams) error {
	_, err := q.db.Exec(ctx, markAsRead, arg.ConversationID, arg.UserID)
	return err
}

const markOutboxFailed = `-- name: MarkOutboxFailed :exec
UPDATE outbox
SET retry_count = retry_count + 1,
    last_retry_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkOutboxFailed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxFailed, id)
	return err
}

const markOutboxProcessed = `-- name: MarkOutboxProcessed :exec
UPDATE outbox
SET processed_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkOutboxProcessed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxProcessed, id)
	return err
}

const moveOutboxToDLQ = `-- name: MoveOutboxToDLQ :exec

INSERT INTO outbox_dlq (original_event_id, aggregate_type, aggregate_id, payload, error_message, retry_count, original_created_at)
SELECT o.id, o.aggregate_type, o.aggregate_id, o.payload, $2, o.retry_count, o.created_at
FROM outbox o
WHERE o.id = $1
`

type MoveOutboxToDLQParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

// Dead Letter Queue (DLQ) Operations
func (q *Queries) MoveOutboxToDLQ(ctx context.Context, arg MoveOutboxToDLQParams) error {
	_, err := q.db.Exec(ctx, moveOutboxToDLQ, arg.ID, arg.ErrorMessage)
	return err
}

const replayDLQEvent = `-- name: ReplayDLQEvent :exec
INSERT INTO outbox (aggregate_type, aggregate_id, payload)
SELECT d.aggregate_type, d.aggregate_id, d.payload
FROM outbox_dlq d
WHERE d.id = $1
`

func (q *Queries) ReplayDLQEvent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, replayDLQEvent, id)
	return err
}

const updateConversationLastMessage = `-- name: UpdateConversationLastMessage :exec
UPDATE conversations
SET last_message_content = $2,
    last_message_at = $3
WHERE id = $1
`

type UpdateConversationLastMessageParams struct {
	ID                 pgtype.UUID        `json:"id"`
	LastMessageContent pgtype.Text        `json:"last_message_content"`
	LastMessageAt      pgtype.Timestamptz `json:"last_message_at"`
}

func (q *Queries) UpdateConversationLastMessage(ctx context.Context, arg UpdateConversationLastMessageParams) error {
	_, err := q.db.Exec(ctx, updateConversationLastMessage, arg.ID, arg.LastMessageContent, arg.LastMessageAt)
	return err
}

const upsertConversation = `-- name: UpsertConversation :one
INSERT INTO conversations (id)
VALUES ($1)
ON CONFLICT (id) DO UPDATE SET created_at = conversations.created_at
RETURNING id, created_at, last_message_content, last_message_at
`

func (q *Queries) UpsertConversation(ctx context.Context, id pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, upsertConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.LastMessageContent,
		&i.LastMessageAt,
	)
	return i, err
}
