// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Conversation struct {
	ID                 pgtype.UUID        `json:"id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	LastMessageContent pgtype.Text        `json:"last_message_content"`
	LastMessageAt      pgtype.Timestamptz `json:"last_message_at"`
}

type ConversationParticipant struct {
	ConversationID pgtype.UUID        `json:"conversation_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	LastReadAt     pgtype.Timestamptz `json:"last_read_at"`
	JoinedAt       pgtype.Timestamptz `json:"joined_at"`
}

type Message struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	SenderID       pgtype.UUID        `json:"sender_id"`
	Content        string             `json:"content"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Type           string             `json:"type"`
	MediaUrl       pgtype.Text        `json:"media_url"`
	MediaMetadata  []byte             `json:"media_metadata"`
}

type Outbox struct {
	ID            pgtype.UUID        `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	Payload       []byte             `json:"payload"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ProcessedAt   pgtype.Timestamptz `json:"processed_at"`
	RetryCount    int32              `json:"retry_count"`
	LastRetryAt   pgtype.Timestamptz `json:"last_retry_at"`
}

type OutboxDlq struct {
	ID                pgtype.UUID        `json:"id"`
	OriginalEventID   pgtype.UUID        `json:"original_event_id"`
	AggregateType     string             `json:"aggregate_type"`
	AggregateID       pgtype.UUID        `json:"aggregate_id"`
	Payload           []byte             `json:"payload"`
	ErrorMessage      pgtype.Text        `json:"error_message"`
	RetryCount        int32              `json:"retry_count"`
	OriginalCreatedAt pgtype.Timestamptz `json:"original_created_at"`
	MovedToDlqAt      pgtype.Timestamptz `json:"moved_to_dlq_at"`
}
